import { marked } from "marked";
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const inputFile = join(__dirname, "ESSAY.md");
const outputFile = join(__dirname, "essay-autogenerated.html");

// Read the markdown file
const markdown = readFileSync(inputFile, "utf-8");

// Configure marked to open links in new tab
const renderer = new marked.Renderer();

renderer.link = ({ href, title, text }) => {
    const titleAttr = title ? ` title="${title}"` : "";
    return `<a href="${href}"${titleAttr} target="_blank" rel="noopener">${text}</a>`;
};

marked.setOptions({
    renderer,
    gfm: true,
    breaks: false,
});

// Parse and generate HTML
const html = marked.parse(markdown);

// Write the output
writeFileSync(outputFile, html.trim() + "\n");

console.log(`Generated: ${outputFile}`);
